In [2]:
import numpy as np
import pandas as pd
a = list(np.random.randn(20))
b = list(np.random.randn(20))
c = list(np.random.randn(20))

dt = {'col1': list(np.random.randn(20)),'col2':list(np.random.randn(20)),'col3':list(np.random.randn(20))}
dt_f = pd.DataFrame(dt,columns = ['col1','col2','col3'])

dt_f.columns = ['A','B','C']

k = int(input('Enter the number of clusters.......'))
print('\n')
print('Number of clusters to be formed are {}'.format(k))
means = dt_f.sample(n=k)
df = dt_f[~dt_f.isin(means)].dropna()
arr_means = np.array(means)
l = len(df)
def Kmeans(iter_means,num):
    dist_list = []
    clusters = []
    merged_dt = pd.DataFrame()
    for i in range(num):
        diff = df-iter_means[i]
        sq = diff**2
        sum_sq = np.sum(sq,axis = 1)
        dist = np.sqrt(sum_sq)
        dist_list.append(dist)
        clusters.append([iter_means[i]])
        merged_dt = pd.concat([merged_dt,dist_list[i]],axis = 1)
    merged_dt.columns = [0,1,2,3]
    min_dist = np.min(merged_dt,axis = 1)
    colindex = merged_dt.columns.where(merged_dt.isin(min_dist))
    cluster_num = colindex.dropna()
    cluster_num = cluster_num.astype(int)
    return cluster_num,clusters
 
clusternum,act_clusters = Kmeans(arr_means,k)

def means_rev(s,index_list,clust):
    for i in range(s):
        if(index_list[i] == 0):
            clust[0].append(df.iloc[i])
        elif(index_list[i] == 1):
            clust[1].append(df.iloc[i])
        elif(index_list[i] == 2):
            clust[2].append(df.iloc[i])
        else:
            clust[3].append(df.iloc[i])
    Rev_means = list(map(lambda x:np.mean(x,axis = 0),clust))
    return Rev_means

revised_means = means_rev(l,clusternum,act_clusters)

Enter the number of clusters.......4


Number of clusters to be formed are 4


In [3]:
clusternum

Int64Index([2, 1, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 1, 1, 0], dtype='int64')

In [4]:
revised_means

[array([ 0.78835179,  0.69120042, -1.61384723]),
 array([-0.54280199, -0.81965037, -0.14285733]),
 array([ 0.31786026, -0.0492523 ,  0.4868521 ]),
 array([ 1.83494985, -1.47491466,  0.11360485])]